type = "about"
title = "About"

[profile]
research_interests = [
  "Algebra",
  "Number Theory",
  "Algebraic Geometry",
  "Computational Algorithms",
  "Riemann Hypothesis (joke)",
]
skills = [
  "LaTeX",
  "Python (Pandas, NumPy, Matplotlib, PyTorch)",
  "R (Statistical Computing)",
  "Mathematical Modelling",
  "Excel VBA",
  "English (Fluent)",
  "Chinese (Native)",
  "MS Office (Word, Excel, PowerPoint)",
  "Adobe Photoshop (Proficient)"
]
hobbies = [
  "Piano (Level 10 Certificate)",
  "Reading",
  "Photography",
  "Suduku",
  "Badminton (Not Very Good)"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

[[sections]]
id = "Education"
type = "cards"
title = "Education"
source = "education.toml"
limit = 3

[[sections]]
id = "featured_awards"
type = "cards"
title = "Selected Awards"
source = "awards.toml"
limit = 5

[[sections]]
id = "featured_experiences"
type = "cards"
title = "Selected Experiences"
source = "experience.toml"
limit = 3

[[sections]]
id = "featured_projects"
type = "cards"
title = "Selected Projects"
source = "projects.toml"
limit = 5

[[sections]]
id = "news"
type = "list"
title = "News"
source = "news.toml"
limit = 5

