[site]
title = "Jingren Zhou"
description = "Personal website of Jingren Zhou, showcasing his research interests, education, publications, teaching, awards, and experiences."
favicon = "/favicon.svg"
last_updated = "April 20, 2026"

[author]
name = "Jingren Zhou"
preferred_name = "Jasper Zhou"
title = "MSc Student in Mathematics and Foundations of Computer Science"
institution = "University of Oxford"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "jasper.zhou0925@gmail.com"
location = "Oxford, United Kingdom"
location_url = "https://www.google.com/maps/search/?api=1&query=University%20of%20Oxford"
location_details = [
  "Mathematical Institute,",
  "University of Oxford,",
  "Oxford, United Kingdom"
]
# google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org/0009-0008-9220-1040"
github = "http://github.com/zhoujasper"
linkedin = "https://www.linkedin.com/in/zhoujingren"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Education"
type = "page"
target = "education"
href = "/education"

[[navigation]]
title = "Projects"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "Experience"
type = "page"
target = "experience"
href = "/experience"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"

[[navigation]]
title = "News"
type = "page"
target = "news"
href = "/news"

[[navigation]]
title = "Mores"
type = "page"
target = "more"
href = "/more"
